# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fio',
            field=models.CharField(max_length=150, verbose_name='Ф.И.О.'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor', verbose_name='Врач'),
        ),
    ]
